#!/bin/bash

##########################################
## Locate this file to ~/.local/bin/
##########################################

export SWT_GTK3=0
export UBUNTU_MENUPROXY=0

pushd $(dirname $(readlink -f $0))
./eclipse
popd
