#!/bin/bash

command=$1

case "$command" in
  launch)
      sudo lxc launch images:centos/7/amd64 centos7-1 -c security.privileged=true
      sudo lxc info centos7-1
      exit 0
      ;;

  list)
      sudo lxc list
      exit 0
      ;;

  enter)
      sudo lxc exec centos7-1 -- bash
      exit 0
      ;;

  stop)
      sudo lxc stop centos7-1
      exit 0
      ;;

  del)
      sudo lxc delete centos7-1
      exit 0
      ;;

  logs)
      exit 0
      ;;

  restart)
      sudo lxc restart centos7-1
      exit 0
      ;;

  start)
      sudo lxc start centos7-1
      exit 0
      ;;
esac
